<?php $category_priority = array(
'Our Work',
'External',
'Events',
'Ideas',
'Interviews',
'Chapters',
'Campaigning',
'Working Groups',
'Data Journalism',
'OKF Projects',
'Bibliographic',
'Business',
'Open Access',
'Open Content',
'Open Data',
'Open Definition',
'Open Geodata',
'Open GLAM',
'Open Government Data',
'Open Knowledge',
'Open Knowledge Definition',
'Open Science',
'Open Standards',
'COMMUNIA',
'Coverage',
'Essays',
'Exemplars',
'Featured Project',
'Free Culture',
'Government',
'Guest post',
'Jobs',
'Legal',
'Linked Open Data',
'Metadata',
'Musings',
'News',
'Newsletter',
'OKF',
'Annotator',
'Bibliographica',
'CKAN',
'datapkg',
'GetTheData',
'KForge',
'LOD2',
'Open Data Commons',
'Open Data Handbook',
'Open Economics',
'Open Shakespeare',
'Open Spending',
'Open Textbooks',
'Public Domain Works',
'School of Data',
'Spending Stories',
'TEXTUS',
'Weaving History',
'Where Does My Money Go',
'Open/Closed',
'Policy',
'Press Releases',
'Public Domain',
'Releases',
'Talks',
'Technical',
'Texts',
'Video',
'visualization',
'Volunteer Opportunities',
'Wikimedia',
); ?>
